# This file mirrors .github/workflows/guardrails.yml
# It exists for documentation and architecture clarity.

# steps:
# - Checkout
# - Configure AWS credentials (OIDC)
# - Terraform init
# - Terraform plan
# - Checkov
# - tfsec
# - OPA 

name: AWS Automated Gaurdrails

on:
  push:
  pull_request:


permissions:
  id-token: write
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::<AccountID>:role/github-actions-oidc-role
        aws-region: ap-south-1

    - name: Terrafomr init
      run: terraform init
      working-directory: terraform

    - name: Terrafomr Plan
      run: terraform plan -out=tfplan.out
      working-directory: terraform

    - name: Convert Plan to JSON
      run: terraform show -json tfplan.out > tfplan.json
      working-directory: terraform

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform
        skip_check: CKV2_AWS_62,CKV_AWS_144

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: terraform

    - name: Install OPA
      run: |
        curl -L -o opa-bin https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod +x opa-bin
        ./opa-bin version

    - name: Run OPA policies
      run: |
        echo "Running OPA policies..."

        ./opa-bin eval \
          --format preety \
          --fail-defined \
          --input terraform/tfplan.json \
          --data opa/policies \
          "data.policies.terraform.aws_ec2.deny"

        ./opa-bin eval \
          --format preety \
          --fail-defined \
          --input terraform/tfplan.json \
          --data opa/policies \
          "data.policies.terraform.aws_iam.deny"

        ./opa-bin eval \
          --format preety \
          --fail-defined \
          --input terraform/tfplan.json \
          --data opa/policies \
          "data.policies.terraform.aws_s3.deny"

        ./opa-bin eval \
          --format preety \
          --fail-defined \
          --input terraform/tfplan.json \
          --data opa/policies \
          "data.policies.terraform.aws_vpc.deny"
