# This file mirrors .github/workflows/guardrails.yml
# It exists for documentation and architecture clarity.
name: AWS Automated Gaurdrails

on:
  push:
  pull_request:


jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terrafomr init
      run: terraform init
      working-directory: terraform

    - name: Terrafomr Plan
      run: terraform plan -out=tfplan.out
      working-directory: terraform

    - name: Convert Plan to JSON
      run: terraform show -json tfplan.out > tfplan.json
